export const LOGIN_USER = "LOGIN_USER";

export const LOGOUT_USER = "LOGOUT_USER";

export const IS_AUTHENTICATED = "IS_AUTHENTICATED";

export const REGISTER = "REGISTER";

export const INVITE_USER = "INVITE_USER";

export const TO_HOME = "TO_HOME";

export const TO_LOGIN = "TO_LOGIN";

export const CONTACT_US = "CONTACT_US";

export const BRAND_PRODUCTS = "BRAND_PRODUCTS";

export const APP_DOWNLOADS = "APP_DOWNLOADS";

export const BENCHMARK_APP_DOWNLOADS = "BENCHMARK_APP_DOWNLOADS";

export const ACTIVATIONS = "ACTIVATIONS";

export const ACTIVATIONS_BENCHMARK = "ACTIVATIONS_BENCHMARK";

export const ACTIVE_USERS = "ACTIVE_USERS";

export const ACTIVE_USERS_BENCHMARK = "ACTIVE_USERS_BENCHMARK";

export const APP_OPENS = "APP_OPENS";

export const APP_OPENS_BENCHMARK = "APP_OPENS_BENCHMARK";

export const WEAR_FREQUENCY = "WEAR_FREQUENCY";

export const WEAR_FREQUENCY_BENCHMARK = "WEAR_FREQUENCY_BENCHMARK";

export const TOP_LOCATION = "TOP_LOCATION";

export const TOP_LOCATION_BENCHMARK = "TOP_LOCATION_BENCHMARK";

export const USAGE_DROP_INSIGHT = "USAGE_DROP_INSIGHT";

export const TOTAL_ACTIVATIONS = "TOTAL_ACTIVATIONS";

export const UNIVERSITIES_INSIGHT = "UNIVERSITIES_INSIGHT";

export const SCHOOLS_INSIGHT = "SCHOOLS_INSIGHT";

export const OUTGOING = "OUTGOING";

export const EVERYDAY_USAGE = "EVERYDAY_USAGE";

export const TRENDING_ITEM = "TRENDING_ITEM";

export const INSIGHTS = "INSIGHTS";

export const DATABOXES = "DATABOXES";

export const BENCHMARK_DATABOXES = "BENCHMARK_DATABOXES";